#!/usr/bin/env bash
#
# This is just a temporary wrapper to get folk used to starting up PyAIMt
# in a different manner.
#

echo "This script is deprecated and will vanish in a future version."
echo "PyAIMt should be started with: python PyAIMt.py"
sleep 2
python ./PyAIMt.py
